services:
  user_db:
    image: bitnami/postgresql:16
    container_name: user_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - user_db_data:/bitnami/postgresql
    # networks:
    #   - user_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api_user
  #   environment:
  #     - POSTGRESQL_USERNAME=${POSTGRES_USER}
  #     - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRESQL_DATABASE=${POSTGRES_DB}
  #     - PORT=${PORT}
  #     - JWT_SECRET=${JWT_SECRET}
  #   ports:
  #     - '3333:3333'
  #   expose:
  #     - 3333
  #   depends_on:
  #     user_db:
  #       condition: service_healthy
  #   volumes:
  #     - ./src:/app/src
  #   networks:
  #     - user_network

volumes:
  user_db_data:
    driver: local
# networks:
#   user_network:
#     driver: bridge
